---
title: "psychencode_hg37_hg38"
author: "sabrina-mi"
date: "2020-09-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(RSQLite)
library(tidyverse)
conn <- dbConnect(RSQLite::SQLite(), "/Users/sabrinami/Github/psychencode/models/psychencode_model/psychencode.db")
weights <- dbGetQuery(conn, 'SELECT * FROM weights')
extra <- dbGetQuery(conn, 'SELECT * FROM extra')
dbDisconnect(conn)

conn <- dbConnect(RSQLite::SQLite(), "/Users/sabrinami/Github/psychencode/models/psychencode_model/psychencode_hg38.db")
mapping <- dbGetQuery(conn, 'SELECT rsid, varID FROM weights')
mapping <- unique(mapping)
dbDisconnect(conn)

weights <- inner_join(weights, mapping, by = "rsid")
weights <- rename(weights, varID = varID.x, varID_hg38 = varID.y)
weights <- weights[, c(1,2,3,7,4,5,6)]
```

```{r}
extra <- weights %>% group_by(gene) %>% summarise(n.snps.in.model = n())
extra$genename <- NA
extra$pred.perf.R2 <- NA
extra$pred.perf.pval <- NA
extra$pred.perf.qval <- NA
extra <- extra[c(1, 3, 2, 4, 5, 6)]
```

```{r}
conn <- dbConnect(RSQLite::SQLite(), "/Users/sabrinami/Github/psychencode/models/psychencode_model/psychencode_hg37_hg38.db")
dbWriteTable(conn, "weights", weights)
dbWriteTable(conn, "extra", extra)
dbDisconnect(conn)

```

